---
- name: Install prerequisites
  package:
    name:
      - firewalld
      - curl
      - gnupg2
      - postfix
      - ca-certificates
    state: present

# Set environment variables
  environment:
    LC_ALL: "en_GB.UTF-8"

# Disable ufw
- name: Disable and stop ufw
  service:
   name: ufw
   enabled: no
   state: stopped

# Set up firewall
- name: Enable and start firewalld
  service:
    name: firewalld
    enabled: yes
    state: started

- name: Add http rule to firewalld
  shell: firewall-cmd --add-service=http --permanent

- name: Add https rule to firewalld
  shell:  firewall-cmd --add-service=https --permanent

- name: Restart firewalld
  service:
    name: firewalld
    state: restarted

# Setup postfix
- name: Start postfix
  service:
    name: postfix
    state: started
    enabled: yes

# Install Gitlab
- name: Add gitlab repo
  shell: curl {{ gitlab_repo }} | sudo bash

- name: Install Gitlab
  package:
    name: "{{ gitlab_version }}"
    state: present
